version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven and verifying environment...
      - mvn -v
      - java -version

  pre_build:
    commands:
      - echo Cleaning and validating project...
      - mvn clean validate -Dmaven.test.skip=true -X

  build:
    commands:
      - echo Building Maven project...
      - mvn package -Dmaven.test.skip=true -X

  post_build:
    commands:
      - echo Build completed successfully.
      - ls -l target/ || echo "No target folder found."

artifacts:
  files:
    - target/*.jar
  discard-paths: yes
