version: 0.2
phases:
  install:
    commands:
      - sudo yum install -y java-17-amazon-corretto-devel maven
      - java -version
      - mvn -version
      
  build:
    commands:
      - clean package
