version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Using Java version:"
      - java -version
      - echo "Using Maven version:"
      - mvn -v

  build:
    commands:
      - echo "Starting Maven build in debug mode..."
      - mvn clean package -Dmaven.test.skip=true -e -X

artifacts:
  files:
    - target/*.jar
  discard-paths: yes
