version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing project dependencies...
      - mvn dependency:resolve

  pre_build:
    commands:
      - echo Pre-build validation...
      - mvn validate

  build:
    commands:
      - echo Building Maven project...
      - mvn clean package -Dmaven.test.skip=true

  post_build:
    commands:
      - echo Build completed successfully.
      - echo Listing target directory...
      - ls -l target/

artifacts:
  files:
    - target/*.jar
  discard-paths: yes
