version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - sudo yum install -y fontconfig java-17-amazon-corretto-devel maven
      - echo "=== Verification ==="
      - java -version
      - mvn -version

  build:
    commands:
      - echo "Building with Maven..."
      - mvn clean package -DskipTests
