version: 0.2

phases:
  install:
    commands:
      - echo "Installing Java and Maven..."
      - yum install -y java-17-amazon-corretto-devel maven
      - java -version
      - mvn -version
  build:
    commands:
      - echo "Building with Maven..."
      - maven clean package -DskipTests

